name: Lightweight CI/CD Pipeline

on: [push]

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code from Repository
        uses: actions/checkout@v4

      - name: Setup Node Runtime Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Application Dependencies
        run: npm install

      - name: Execute Automated Unit Tests
        run: npm test

      - name: Deploy Live to Vercel Production Server
        uses: amondnet/vercel-action@latest
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
